services:
  postgres_db:
    container_name: postgres-ztbd
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: extensive_testing
    volumes:
      - ./postgres/db.sql:/docker-entrypoint-initdb.d/db.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mysql:
    image: mysql:9.2
    container_name: mysql-ztbd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_USER: testing
      MYSQL_PASSWORD: extensive_testing
      MYSQL_DATABASE: ztbd
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  postgres-data:
  mysql-data:
