services:
  initializer:
    container_name: db-initializer
    build:
      context: ./parser/
    environment:
      BEGIN_YEAR: 2010
      END_YEAR: 2024
      VOLUME_DIR: "/app/data"
    volumes:
      - ./parser/data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_started
      mongo7:
        condition: service_started
      mongo8:
        condition: service_started
  postgres:
    container_name: postgres-ztbd
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: extensive_testing
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      retries: 3
  mysql:
    image: mysql:9.2
    container_name: mysql-ztbd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_USER: testing
      MYSQL_PASSWORD: extensive_testing
      MYSQL_DATABASE: ztbd
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  mongo7:
    container_name: mongo7-ztbd
    image: mongo:7
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: ztbd
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd
    volumes:
      - mongo7-data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  mongo8:
    container_name: mongo8-ztbd
    image: mongo:8
    restart: always
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_DATABASE: ztbd
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: passwd
    volumes:
      - mongo8-data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

volumes:
  postgres-data:
  mysql-data:
  mongo7-data:
  mongo8-data:
